// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGJFm3xtvA4bufPDhrlHUZvBp51WHo9KY',
    appId: '1:825687003647:web:438669bf30b7f726d7d7ca',
    messagingSenderId: '825687003647',
    projectId: 'smart-ai-product-app-7ab96',
    authDomain: 'smart-ai-product-app-7ab96.firebaseapp.com',
    storageBucket: 'smart-ai-product-app-7ab96.firebasestorage.app',
    measurementId: 'G-SBST3066Q5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFBZOo7O-4dLvLRGgJxCQyyX6rbKwR2-U',
    appId: '1:825687003647:android:2aef33cb3c979d77d7d7ca',
    messagingSenderId: '825687003647',
    projectId: 'smart-ai-product-app-7ab96',
    storageBucket: 'smart-ai-product-app-7ab96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa7PD6ysgt2UMotIGiZc5V4eLzpxgJg-4',
    appId: '1:825687003647:ios:a8b3833c41ddf60cd7d7ca',
    messagingSenderId: '825687003647',
    projectId: 'smart-ai-product-app-7ab96',
    storageBucket: 'smart-ai-product-app-7ab96.firebasestorage.app',
    iosClientId: '825687003647-n18r3pqcijo0j94nvnjka0trbc3tajb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flowmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa7PD6ysgt2UMotIGiZc5V4eLzpxgJg-4',
    appId: '1:825687003647:ios:a8b3833c41ddf60cd7d7ca',
    messagingSenderId: '825687003647',
    projectId: 'smart-ai-product-app-7ab96',
    storageBucket: 'smart-ai-product-app-7ab96.firebasestorage.app',
    iosClientId: '825687003647-n18r3pqcijo0j94nvnjka0trbc3tajb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flowmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGJFm3xtvA4bufPDhrlHUZvBp51WHo9KY',
    appId: '1:825687003647:web:9871fa6504d31d0ed7d7ca',
    messagingSenderId: '825687003647',
    projectId: 'smart-ai-product-app-7ab96',
    authDomain: 'smart-ai-product-app-7ab96.firebaseapp.com',
    storageBucket: 'smart-ai-product-app-7ab96.firebasestorage.app',
    measurementId: 'G-ZN1XC4S0BJ',
  );

}